config.reload.automatic: true
config.reload.interval: 3s
dead_letter_queue.enable: true
http.host: 0.0.0.0
log.level: info
path.config: /usr/share/logstash/pipeline
pipeline.batch.delay: 50
pipeline.batch.size: 125
pipeline.ordered: auto
pipeline.workers: 2
queue.type: persisted
xpack.monitoring.collection.interval: 10s
xpack.monitoring.elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.elasticsearch.password: changeme
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
